version: "3"
services:
  db:
    hostname: 'db'
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: pizzeria_db
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "@Arianna22"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/Pizza-Delivery-System
    ports:
      - "8000:8000"
    depends_on:
      - db