version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Pizza-Delivery-System
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    hostname: 'db'
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: pizzeria_db
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "@Arianna22"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
      start_interval: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A pizzeria worker --loglevel=info
    volumes:
      - .:/Pizza-Delivery-System
    depends_on:
      - db
      - redis
      - web