# Generated by Django 4.1.7 on 2023-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pizza_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
