# Generated by Django 4.1.7 on 2023-09-27 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pizzaorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
